# Generated by Django 3.2.15 on 2023-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='district',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Kerala', max_length=100),
        ),
    ]
