# Generated by Django 3.2.15 on 2023-03-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
